#!/usr/bin/env bash

USER='rhettl'
NAME='toPdf'
TAG='node-wkhtmltopdf'
ID_FILE='./.dockerid'
ID=''

PORT=8080
if [ ${1} != '' ]; then
  if [[ ${1} =~ ^[0-9]+$ ]] && [ ${1} -gt 0 ]; then
    PORT=${1}
  else
    (>&2 echo "port is not a number > 0")
    echo
    echo "USAGE: docker-rebuild [port]"
    echo "port defaults to 8080"
    exit 1
  fi
fi

if [ -s ${ID_FILE} ]; then
  ID=`cat ${ID_FILE}`
  echo "Docker ID: ${ID}"
  if [[ $(docker ps --no-trunc --quiet | grep ${ID}) != '' ]]; then
    docker stop ${ID}
    docker rm ${ID}
  fi
fi

docker build -t "${USER}/${TAG}" .
ID=`docker run -d -p "${PORT}":8080 -e PORT=8080 --name "${NAME}" "${USER}/${TAG}"`

echo ${ID} > ${ID_FILE}
